language: python
env:
    - TOX_ENV=py27
    - TOX_ENV=py35
python: 3.5
script: tox -e $TOX_ENV
install: pip install tox
addons:
    apt:
        packages:
            - python-dev
            - python3-dev
